export enum MessageTypeEnum {
  THE_CODE_HAS_ALREADY_BEEN_SENT_TO_THE_EMAIL = 'THE_CODE_HAS_ALREADY_BEEN_SENT_TO_THE_EMAIL',
  PASSWORD_SUCCESSFULLY_CHANGED = 'PASSWORD_SUCCESSFULLY_CHANGED',
  PASSWORD_HAS_BEEN_SENT_TO_THE_EMAIL = 'PASSWORD_HAS_BEEN_SENT_TO_THE_EMAIL',
}
